### ISSUE TITLE
Chatter App Typo

### ISSUE THREAD

**Issue by thejohncotton** [elixir-bridge/elixir-bridge.github.io#129]
Old reference: 
```elixir
def recent_messages(limit \\ 10) do
  Chatter.Repo.all(Message, limit: limit)
end
```
rather than 
```elixir
def recent_messages(limit \\ 10) do
  Chatter.Repo.all(Chatter.Message, limit: limit)
end
```
There is a duplicate page in the repo with the correct reference, but the chat app tutorial links to an older page.

**Comment by aneyzberg** [comment]
Thank you so much for all the PR's. This is hugely helpful!
