### ISSUE TITLE
Wrong version mentioned in installation guide?

### ISSUE THREAD

**Issue by krishna-404** [elixir-bridge/elixir-bridge.github.io#157]
Hi! I am new to this & started learning from the website. In the Elixir Installation guide (https://elixirbridge.org/01_Installfest/05-install-elixir-and-phoenix.html), it seems that wrong version number is mentioned.

The version number mentioned is 1.5.1. As per elixir website the latest version released in Jun '24 is 1.17.1. Is it supposed to be 1.15.1?

Hapy to make a PR if thats the case.

**Comment by photomattmills** [comment]
No, the instructions are just very out of date. The lessons were mostly written 2016-2017. Probably you should take a look at https://elixir-lang.org/install.html for up-to-date instructions. Also, Elixir School: https://elixirschool.com/en might be better for learning, as it's maintained and this isn't really.

**Comment by krishna-404** [comment]
Thanks for such a quick reply @photomattmills. Its good to know before I mess up something 😓
