### ISSUE TITLE
Addressing consistency with code example formatting

### ISSUE THREAD

**Issue by javierjulio** [elixir-bridge/elixir-bridge.github.io#72]
I've noticed an inconsistent way of showing the result of an expression in an IEx code example. Since its not explained that a `#` in shell is a comment, I figure several of the examples that look like the following (taken from List and Tuples, second exmaple):

```sh
iex> length [1, 2, 3] # 3
iex> [1] ++ [2] # [1, 2]
iex> [1, 2, 3] -- [2] # [1, 3]
```

Could instead be updated to:

```sh
iex> length [1, 2, 3]
3
iex> [1] ++ [2]
[1, 2]
iex> [1, 2, 3] -- [2]
[1, 3]
```

Which would also make it consistent with examples not just in the same chapter but across the guide.  

I feel like beginners would have an easier time with the formatting in the latter as its showing the result after their expression is evaluated and would also match the same as to what they see in their IEx console when they run said code.

Would you be open to a PR to make the console output examples consistent?

**Comment by aneyzberg** [comment]
@javierjulio That sounds great!

**Comment by aneyzberg** [comment]
this is definitely a work in progress so feedback like this is really helpful.

**Comment by javierjulio** [comment]
@aneyzberg that's what I figured. I'll get on it so its ready for the event! Thanks!

**Comment by aneyzberg** [comment]
thank you!
